### ISSUE TITLE
Docker compose version 3.4 doesn't match the script contents

### ISSUE THREAD

**Issue by cpwnd** [jlu-ilr-hydro/odmf-docker#3]
I got the following message when start via compose.
```
$ docker-compose up -d
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

I fixed it with this really tiny pull request.   #2 

After changing the version to 3.3 everything starts without a problem and I could open the start page :) Great to see the running docker setup of odmf.

**Comment by philippkraft** [comment]
Ok, on Unbuntu 20.04 3.4 was ok, on Windows even 3.8. So we go even deeper - no problem as we are not doing anything fancy.
